// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// ClusterInfo represents status of a resource bundle rollout for a cluster.
public struct ClusterInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. gkehub membership of target cluster
  public var membership: Swift.String = Swift.String()

  /// Output only. Desired state for the resource bundle.
  public var desired: ResourceBundleDeploymentInfo? = nil

  /// Output only. Initial state of the resource bundle prior to the deployment.
  public var initial: ResourceBundleDeploymentInfo? = nil

  /// Output only. Current state of the resource bundle.
  public var current: ResourceBundleDeploymentInfo? = nil

  /// Output only. State of the rollout for the cluster.
  public var state: ClusterInfo.State = ClusterInfo.State()

  /// Output only. Unordered list. Messages convey additional information related
  /// to the deployment.
  public var messages: [Swift.String] = []

  /// Output only. Timestamp when reconciliation starts.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Timestamp when reconciliation ends.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `ClusterInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ClusterInfo().with { $0.membership = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// State of the rollout for the cluster.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified state.
    case unspecified
    /// Waiting state.
    case waiting
    /// In progress state.
    case inProgress
    /// Stalled state.
    case stalled
    /// Completed state.
    case completed
    /// Aborted state.
    case aborted
    /// Cancelled state.
    case cancelled
    /// Error state.
    case error
    /// Unchanged state.
    case unchanged
    /// Skipped state.
    case skipped
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .waiting: return 1
      case .inProgress: return 2
      case .stalled: return 3
      case .completed: return 4
      case .aborted: return 5
      case .cancelled: return 6
      case .error: return 7
      case .unchanged: return 8
      case .skipped: return 9
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .waiting: return "WAITING"
      case .inProgress: return "IN_PROGRESS"
      case .stalled: return "STALLED"
      case .completed: return "COMPLETED"
      case .aborted: return "ABORTED"
      case .cancelled: return "CANCELLED"
      case .error: return "ERROR"
      case .unchanged: return "UNCHANGED"
      case .skipped: return "SKIPPED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "WAITING": self = .waiting
      case "IN_PROGRESS": self = .inProgress
      case "STALLED": self = .stalled
      case "COMPLETED": self = .completed
      case "ABORTED": self = .aborted
      case "CANCELLED": self = .cancelled
      case "ERROR": self = .error
      case "UNCHANGED": self = .unchanged
      case "SKIPPED": self = .skipped
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .waiting
      case 2: self = .inProgress
      case 3: self = .stalled
      case 4: self = .completed
      case 5: self = .aborted
      case 6: self = .cancelled
      case 7: self = .error
      case 8: self = .unchanged
      case 9: self = .skipped
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .waiting: return try container.encode(1)
      case .inProgress: return try container.encode(2)
      case .stalled: return try container.encode(3)
      case .completed: return try container.encode(4)
      case .aborted: return try container.encode(5)
      case .cancelled: return try container.encode(6)
      case .error: return try container.encode(7)
      case .unchanged: return try container.encode(8)
      case .skipped: return try container.encode(9)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.configdelivery.v1.ClusterInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
