// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol ConfigDeliveryStub: Sendable {
    func listResourceBundles(
      request: ListResourceBundlesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigDeliveryV1.ListResourceBundlesResponse

    func getResourceBundle(
      request: GetResourceBundleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigDeliveryV1.ResourceBundle

    func createResourceBundle(
      request: CreateResourceBundleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateResourceBundle(
      request: UpdateResourceBundleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteResourceBundle(
      request: DeleteResourceBundleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listFleetPackages(
      request: ListFleetPackagesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigDeliveryV1.ListFleetPackagesResponse

    func getFleetPackage(
      request: GetFleetPackageRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigDeliveryV1.FleetPackage

    func createFleetPackage(
      request: CreateFleetPackageRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateFleetPackage(
      request: UpdateFleetPackageRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteFleetPackage(
      request: DeleteFleetPackageRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listReleases(
      request: ListReleasesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigDeliveryV1.ListReleasesResponse

    func getRelease(
      request: GetReleaseRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigDeliveryV1.Release

    func createRelease(
      request: CreateReleaseRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateRelease(
      request: UpdateReleaseRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteRelease(
      request: DeleteReleaseRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listVariants(
      request: ListVariantsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigDeliveryV1.ListVariantsResponse

    func getVariant(
      request: GetVariantRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigDeliveryV1.Variant

    func createVariant(
      request: CreateVariantRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateVariant(
      request: UpdateVariantRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteVariant(
      request: DeleteVariantRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listRollouts(
      request: ListRolloutsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigDeliveryV1.ListRolloutsResponse

    func getRollout(
      request: GetRolloutRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigDeliveryV1.Rollout

    func suspendRollout(
      request: SuspendRolloutRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func resumeRollout(
      request: ResumeRolloutRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func abortRollout(
      request: AbortRolloutRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
