// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A `FleetPackage` resource in the Config Delivery API.
///
/// A `FleetPackage` defines a package through which kubernetes
/// configuration is deployed to a fleet of kubernetes clusters.
public struct FleetPackage: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. Name of the `FleetPackage`. Format is
  /// `projects/{project}/locations/{location}/fleetPackages/{fleetPackage}`.
  /// The `fleetPackage` component must match
  /// `[a-z][a-z0-9\-]{0,62}`
  public var name: Swift.String = Swift.String()

  /// Output only. Time at which the `FleetPackage` was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Most recent time at which the `FleetPackage` was updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. Labels are attributes that can be set and used by both the
  /// user and by Config Delivery. Labels must meet the following constraints:
  ///
  /// * Keys and values can contain only lowercase letters, numeric characters,
  /// underscores, and dashes.
  /// * All characters must use UTF-8 encoding, and international characters are
  /// allowed.
  /// * Keys must start with a lowercase letter or international character.
  /// * Each resource is limited to a maximum of 64 labels.
  ///
  /// Both keys and values are additionally constrained to be <= 128 bytes.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Required. Information specifying the source of kubernetes configuration to
  /// deploy.
  public var resourceBundleSelector: FleetPackage.ResourceBundleSelector? = nil

  /// Optional. Configuration to select target clusters to deploy kubernetes
  /// configuration to.
  public var target: FleetPackage.Target? = nil

  /// Optional. The strategy to use to deploy kubernetes configuration to
  /// clusters.
  public var rolloutStrategy: RolloutStrategy? = nil

  /// Required. Information specifying how to map a `ResourceBundle` variant to a
  /// target cluster.
  public var variantSelector: FleetPackage.VariantSelector? = nil

  /// Output only. Information containing the rollout status of the
  /// `FleetPackage` across all the target clusters.
  public var info: FleetPackageInfo? = nil

  /// Optional. Information around how to handle kubernetes resources at the
  /// target clusters when the `FleetPackage` is deleted.
  public var deletionPropagationPolicy: DeletionPropagationPolicy = DeletionPropagationPolicy()

  /// Optional. The desired state of the fleet package.
  public var state: FleetPackage.State = FleetPackage.State()

  /// Initialize a new instance of `FleetPackage`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FleetPackage().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Information specifying the source of kubernetes configuration to deploy.
  public struct ResourceBundleSelector: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// source can be a directly pushed `ResourceBundle` or
    /// `CloudBuildRepository` containing the kubernetes configuration.
    public var source: OneOf_Source? = nil

    /// Initialize a new instance of `ResourceBundleSelector`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ResourceBundleSelector().with { $0.resourceBundle = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case resourceBundle = "resourceBundle"
      case cloudBuildRepository = "cloudBuildRepository"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var source: OneOf_Source? = nil
      let sourceCheckAndSet = {
        if source != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'source'"))
        }
        source = $0
      }
      if let resourceBundle = try container.decodeIfPresent(
        FleetPackage.ResourceBundleTag?.self, forKey: .resourceBundle)
      {
        try sourceCheckAndSet(.resourceBundle(resourceBundle))
      }
      if let cloudBuildRepository = try container.decodeIfPresent(
        FleetPackage.CloudBuildRepository?.self, forKey: .cloudBuildRepository)
      {
        try sourceCheckAndSet(.cloudBuildRepository(cloudBuildRepository))
      }
      self.source = source
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.source {
        switch choice {
        case .resourceBundle(let value):
          try container.encode(value, forKey: .resourceBundle)
        case .cloudBuildRepository(let value):
          try container.encode(value, forKey: .cloudBuildRepository)
        }
      }
    }

    /// source can be a directly pushed `ResourceBundle` or
    /// `CloudBuildRepository` containing the kubernetes configuration.
    public enum OneOf_Source: Codable, Equatable, Sendable {
      /// Information specifying `ResourceBundle`.
      indirect case resourceBundle(FleetPackage.ResourceBundleTag?)
      /// Information specifying `CloudBuildRepository`.
      indirect case cloudBuildRepository(FleetPackage.CloudBuildRepository?)
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.configdelivery.v1.FleetPackage.ResourceBundleSelector"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// ResourceBundleTag contains the information to refer to a release for a
  /// `ResourceBundle`.
  public struct ResourceBundleTag: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. Name of the `ResourceBundle`.
    /// Format is projects/{p}/locations/{l}/resourceBundles/{r}.
    public var name: Swift.String = Swift.String()

    /// Required. Tag refers to a version of the release in a `ResourceBundle`.
    /// This is a Git tag in the semantic version format `vX.Y.Z`.
    public var tag: Swift.String = Swift.String()

    /// Initialize a new instance of `ResourceBundleTag`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ResourceBundleTag().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.configdelivery.v1.FleetPackage.ResourceBundleTag"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// CloudBuildRepository contains information about fetching Kubernetes
  /// configuration from a `CloudBuildRepository`.
  public struct CloudBuildRepository: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. Name of the cloud build repository.
    /// Format is projects/{p}/locations/{l}/connections/{c}/repositories/{r}.
    public var name: Swift.String = Swift.String()

    /// Optional. path to the directory or file within the repository that
    /// contains the kubernetes configuration. If unspecified, path is assumed to
    /// the top level root directory of the repository.
    public var path: Swift.String = Swift.String()

    /// Required. git tag of the underlying git repository.
    /// The git tag must be in the semantic version format `vX.Y.Z`.
    public var tag: Swift.String = Swift.String()

    /// Required. Google service account to use in CloudBuild triggers to fetch
    /// and store kubernetes configuration.
    public var serviceAccount: Swift.String = Swift.String()

    /// variants_pattern is the configuration for how to read the repository
    /// to find variants.
    public var variants: OneOf_Variants? = nil

    /// Initialize a new instance of `CloudBuildRepository`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CloudBuildRepository().with { $0.variantsPattern = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case variantsPattern = "variantsPattern"
      case name = "name"
      case path = "path"
      case tag = "tag"
      case serviceAccount = "serviceAccount"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.name = try container.decode(Swift.String.self, forKey: .name)
      self.path = try container.decode(Swift.String.self, forKey: .path)
      self.tag = try container.decode(Swift.String.self, forKey: .tag)
      self.serviceAccount = try container.decode(Swift.String.self, forKey: .serviceAccount)

      var variants: OneOf_Variants? = nil
      let variantsCheckAndSet = {
        if variants != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'variants'"))
        }
        variants = $0
      }
      if let variantsPattern = try container.decodeIfPresent(
        Swift.String.self, forKey: .variantsPattern)
      {
        try variantsCheckAndSet(.variantsPattern(variantsPattern))
      }
      self.variants = variants
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.path, forKey: .path)
      try container.encode(self.tag, forKey: .tag)
      try container.encode(self.serviceAccount, forKey: .serviceAccount)

      if let choice = self.variants {
        switch choice {
        case .variantsPattern(let value):
          try container.encode(value, forKey: .variantsPattern)
        }
      }
    }

    /// variants_pattern is the configuration for how to read the repository
    /// to find variants.
    public enum OneOf_Variants: Codable, Equatable, Sendable {
      /// Optional. variants_pattern is a glob pattern that will be used to find
      /// variants in the repository. Examples: `variants/*.yaml`, `us-*`
      case variantsPattern(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.configdelivery.v1.FleetPackage.CloudBuildRepository"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The target defines different ways to target set of kubernetes clusters.
  public struct Target: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// target for the fleet package.
    public var target: OneOf_Target? = nil

    /// Initialize a new instance of `Target`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Target().with { $0.fleet = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case fleet = "fleet"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var target: OneOf_Target? = nil
      let targetCheckAndSet = {
        if target != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'target'"))
        }
        target = $0
      }
      if let fleet = try container.decodeIfPresent(Fleet?.self, forKey: .fleet) {
        try targetCheckAndSet(.fleet(fleet))
      }
      self.target = target
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.target {
        switch choice {
        case .fleet(let value):
          try container.encode(value, forKey: .fleet)
        }
      }
    }

    /// target for the fleet package.
    public enum OneOf_Target: Codable, Equatable, Sendable {
      /// The GKE fleet information.
      indirect case fleet(Fleet?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.configdelivery.v1.FleetPackage.Target"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// VariantSelector contains information for selecting a variant in
  /// `ResourceBundle` to deploy to a target cluster.
  public struct VariantSelector: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// strategy for selecting a variant.
    public var strategy: OneOf_Strategy? = nil

    /// Initialize a new instance of `VariantSelector`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = VariantSelector().with { $0.variantNameTemplate = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case variantNameTemplate = "variantNameTemplate"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var strategy: OneOf_Strategy? = nil
      let strategyCheckAndSet = {
        if strategy != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'strategy'"))
        }
        strategy = $0
      }
      if let variantNameTemplate = try container.decodeIfPresent(
        Swift.String.self, forKey: .variantNameTemplate)
      {
        try strategyCheckAndSet(.variantNameTemplate(variantNameTemplate))
      }
      self.strategy = strategy
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.strategy {
        switch choice {
        case .variantNameTemplate(let value):
          try container.encode(value, forKey: .variantNameTemplate)
        }
      }
    }

    /// strategy for selecting a variant.
    public enum OneOf_Strategy: Codable, Equatable, Sendable {
      /// Required. variant_name_template is a template that can refer to
      /// variables containing cluster membership metadata such as location,
      /// name, and labels to generate the name of the variant for a target
      /// cluster. The variable syntax is similar to the unix shell variables.
      ///
      /// Available variables are `${membership.name}`, `${membership.location}`,
      /// `${membership.project}` and `${membership.labels['label_name']}`.
      ///
      /// If you want to deploy a specific variant, say "default" to all the
      /// clusters, you can use "default" (string without any variables) as
      /// the variant_name_template.
      case variantNameTemplate(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.configdelivery.v1.FleetPackage.VariantSelector"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// State indicates the desired state for the fleet package.
  /// Unspecified value is equivalent to `ACTIVE`. If state is set to
  /// `SUSPENDED`, active rollout (if any) will continue but no new rollouts will
  /// be scheduled.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified state.
    case unspecified
    /// `FleetPackage` is intended to be active.
    case active
    /// `FleetPackage` is intended to be suspended.
    case suspended
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .suspended: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .suspended: return "SUSPENDED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "SUSPENDED": self = .suspended
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .suspended
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .active: return try container.encode(1)
      case .suspended: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.configdelivery.v1.FleetPackage"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
