// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// RolloutInfo represents the state of the `FleetPackage` at all the
/// clusters the rollout is targeting.
public struct RolloutInfo: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. state contains the overall status of the Rollout.
  public var state: RolloutInfo.State = RolloutInfo.State()

  /// Output only. Time when the rollout started.
  public var startTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Time when the rollout completed.
  public var endTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Message containing additional information related to the
  /// rollout.
  public var message: Swift.String = Swift.String()

  /// Output only. Rollout strategy info represents the status of execution of
  /// rollout strategy.
  public var rolloutStrategyInfo: RolloutStrategyInfo? = nil

  /// Initialize a new instance of `RolloutInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RolloutInfo().with { $0.state = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// State of the rollout
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified state.
    case unspecified
    /// Rollout completed.
    case completed
    /// Rollout suspended.
    case suspended
    /// Rollout aborted.
    case aborted
    /// Rollout in progress.
    case inProgress
    /// Rollout stalled.
    case stalled
    /// Rollout cancelled.
    case cancelled
    /// Rollout aborting.
    case aborting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .completed: return 1
      case .suspended: return 2
      case .aborted: return 3
      case .inProgress: return 5
      case .stalled: return 6
      case .cancelled: return 7
      case .aborting: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .completed: return "COMPLETED"
      case .suspended: return "SUSPENDED"
      case .aborted: return "ABORTED"
      case .inProgress: return "IN_PROGRESS"
      case .stalled: return "STALLED"
      case .cancelled: return "CANCELLED"
      case .aborting: return "ABORTING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "COMPLETED": self = .completed
      case "SUSPENDED": self = .suspended
      case "ABORTED": self = .aborted
      case "IN_PROGRESS": self = .inProgress
      case "STALLED": self = .stalled
      case "CANCELLED": self = .cancelled
      case "ABORTING": self = .aborting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .completed
      case 2: self = .suspended
      case 3: self = .aborted
      case 5: self = .inProgress
      case 6: self = .stalled
      case 7: self = .cancelled
      case 8: self = .aborting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .completed: return try container.encode(1)
      case .suspended: return try container.encode(2)
      case .aborted: return try container.encode(3)
      case .inProgress: return try container.encode(5)
      case .stalled: return try container.encode(6)
      case .cancelled: return try container.encode(7)
      case .aborting: return try container.encode(8)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.configdelivery.v1.RolloutInfo"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
