// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Rollout resource represents an instance of `FleetPackage` rollout operation
/// across a fleet. This is a system generated resource and will be read only for
/// end-users. It will be primarily used by the service to process the changes in
/// the `FleetPackage` and other changes in the environment.
public struct Rollout: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. Name of the Rollout. Format is
  /// `projects/{project}/locations/{location}/fleetPackages/{fleet_package}/rollouts/[a-z][a-z0-9\-]{0,62}`.
  public var name: Swift.String = Swift.String()

  /// Reference to the `Release` being rolled out.
  public var release: Swift.String = Swift.String()

  /// Rollout strategy for rolling out `FleetPackage` to clusters.
  public var rolloutStrategy: RolloutStrategy? = nil

  /// Current details of the rollout.
  public var info: RolloutInfo? = nil

  /// Deletion propagation policy of the rollout.
  public var deletionPropagationPolicy: DeletionPropagationPolicy = DeletionPropagationPolicy()

  /// Output only. The time the rollout was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time the rollout was most recently updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `Rollout`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Rollout().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.configdelivery.v1.Rollout"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
