// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Variant represents the content of a `ResourceBundle` variant.
public struct Variant: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. labels to represent any metadata associated with the variant.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Required. Input only. Unordered list. resources contain the kubernetes
  /// manifests (YAMLs) for this variant.
  public var resources: [Swift.String] = []

  /// Identifier. Name follows format of
  /// projects/{project}/locations/{location}/resourceBundles/{resource_bundle}/releases/{release}/variants/{variant}
  public var name: Swift.String = Swift.String()

  /// Output only. [Output only] Create time stamp
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. [Output only] Update time stamp
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Initialize a new instance of `Variant`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Variant().with { $0.labels = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.configdelivery.v1.Variant"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
